apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web-server
  template:
    metadata:
      labels:
        app: python-web-server
    spec:
      containers:
      - name: python-web-server
        image: harish343/webserver:latest # Replace this with your Docker image tag
        ports:
        - containerPort: 80 # Assuming your Flask app runs on port 5000
