apiVersion: v1
kind: Service
metadata:
  name: python-web-service
spec:
  selector:
    app: python-web-server
  ports:
    - protocol: TCP
      port: 80 # The port on which the service will be exposed internally
      targetPort: 80 # The port on which your Flask app is running
  type: LoadBalancer # Expose the service using a LoadBalancer
